services:
  redis:
    image: redis
    restart: always
    container_name: 'redis_authentication_db'
    cpus: 1
    mem_limit: 512m
    ports:
      - '6379:6379'
    volumes:
      - './dev/redis:/authentication/data'
