services:
  user_db:
    image: postgres
    restart: always
    container_name: 'postgres_user_db'
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - './dev/postgres:/user/data'
